### ISSUE TITLE
`@ Macros

### ISSUE THREAD

**Issue by michaelsayersURI** [liam-strand/medford-vscode#4]
Are macros supported?

**Comment by liam-strand** [comment]
Yes! Here's me using the macro autocompletion feature on my machine.

<img width="1123" alt="Screenshot 2023-10-22 at 5 09 11 PM" src="https://github.com/TuftsBCB/medford-vscode/assets/68445012/d1c2c230-57f6-480f-9706-8ac9a30f5785">

**Comment by msayers1** [comment]
I was using ' instead of `. Thanks!

**Comment by liam-strand** [comment]
Glad it's all figured out!

**Comment by msayers1** [comment]
Thanks!
